/**
 * 🐘 NEON — Dual-write para payment_config e api_keys
 * Fire-and-forget: nunca bloqueia o fluxo Firebase principal
 */

import { neonQuery } from './neon-db.js';

// ─────────────────────────────────────────────
// PAYMENT CONFIG (singleton 'global')
// ─────────────────────────────────────────────

export async function neonUpsertPaymentConfig(data: {
  id: string;
  sellerId?: string | null;
  defaultAcquirers?: Record<string, any> | null;
  fees?: Record<string, any> | null;
  config?: Record<string, any> | null;
  updatedBy?: string | null;
  createdAt?: Date;
}): Promise<void> {
  await neonQuery(async (sql) => {
    await sql`
      INSERT INTO payment_config (id, seller_id, default_acquirers, fees, config, updated_by, created_at, updated_at)
      VALUES (
        ${data.id},
        ${data.sellerId ?? null},
        ${data.defaultAcquirers ? JSON.stringify(data.defaultAcquirers) : null},
        ${data.fees ? JSON.stringify(data.fees) : null},
        ${data.config ? JSON.stringify(data.config) : null},
        ${data.updatedBy ?? null},
        ${data.createdAt ?? new Date()},
        NOW()
      )
      ON CONFLICT (id) DO UPDATE SET
        seller_id         = COALESCE(EXCLUDED.seller_id,          payment_config.seller_id),
        default_acquirers = COALESCE(EXCLUDED.default_acquirers,  payment_config.default_acquirers),
        fees              = COALESCE(EXCLUDED.fees,               payment_config.fees),
        config            = COALESCE(EXCLUDED.config,             payment_config.config),
        updated_by        = COALESCE(EXCLUDED.updated_by,         payment_config.updated_by),
        updated_at        = NOW()
    `;
  }, `neonUpsertPaymentConfig(${data.id})`);
}

export async function neonUpdatePaymentConfig(
  id: string,
  updates: {
    defaultAcquirers?: Record<string, any> | null;
    fees?: Record<string, any> | null;
    config?: Record<string, any> | null;
    updatedBy?: string | null;
  }
): Promise<void> {
  if (!id) return;
  await neonQuery(async (sql) => {
    await sql`
      INSERT INTO payment_config (id, updated_at) VALUES (${id}, NOW())
      ON CONFLICT (id) DO UPDATE SET
        default_acquirers = COALESCE(${updates.defaultAcquirers ? JSON.stringify(updates.defaultAcquirers) : null}, payment_config.default_acquirers),
        fees              = COALESCE(${updates.fees ? JSON.stringify(updates.fees) : null},               payment_config.fees),
        config            = CASE
                              WHEN ${updates.config ? JSON.stringify(updates.config) : null} IS NOT NULL
                              THEN payment_config.config || ${updates.config ? JSON.stringify(updates.config) : '{}'}::jsonb
                              ELSE payment_config.config
                            END,
        updated_by        = COALESCE(${updates.updatedBy ?? null}, payment_config.updated_by),
        updated_at        = NOW()
    `;
  }, `neonUpdatePaymentConfig(${id})`);
}

// ─────────────────────────────────────────────
// API KEYS
// ─────────────────────────────────────────────

export async function neonWriteApiKey(data: {
  id: string;
  sellerId: string;
  name: string;
  permissions: string[];
  keyHash: string;
  last4: string;
  active?: boolean;
  autoGenerated?: boolean;
  usageCount?: number;
  createdAt?: Date;
}): Promise<void> {
  await neonQuery(async (sql) => {
    await sql`
      INSERT INTO api_keys (
        id, seller_id, name, permissions, key_hash, last4,
        active, auto_generated, usage_count, created_at, updated_at
      ) VALUES (
        ${data.id},
        ${data.sellerId},
        ${data.name},
        ${JSON.stringify(data.permissions)},
        ${data.keyHash},
        ${data.last4},
        ${data.active ?? true},
        ${data.autoGenerated ?? false},
        ${data.usageCount ?? 0},
        ${data.createdAt ?? new Date()},
        NOW()
      )
      ON CONFLICT (id) DO NOTHING
    `;
  }, `neonWriteApiKey(${data.id})`);
}

export async function neonDeleteApiKey(id: string): Promise<void> {
  if (!id) return;
  await neonQuery(async (sql) => {
    await sql`
      UPDATE api_keys
      SET active = FALSE, updated_at = NOW()
      WHERE id = ${id}
    `;
  }, `neonDeleteApiKey(${id})`);
}
